version: '3'
services:
    mongo:
        image: "mongo:4.0"
        container_name: "mongo"
        restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - "27017:27017"
        command: mongod --smallfiles --logpath=/dev/null # --quiet
